<?php
declare(strict_types=1);

// IsEven SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

IsEvenUtility::setRegistrar(function (IsEvenUtility $u): void {
    $u->clean = [IsEvenClean::class, 'call'];
    $u->done = [IsEvenDone::class, 'call'];
    $u->make_error = [IsEvenMakeError::class, 'call'];
    $u->feature_add = [IsEvenFeatureAdd::class, 'call'];
    $u->feature_hook = [IsEvenFeatureHook::class, 'call'];
    $u->feature_init = [IsEvenFeatureInit::class, 'call'];
    $u->fetcher = [IsEvenFetcher::class, 'call'];
    $u->make_fetch_def = [IsEvenMakeFetchDef::class, 'call'];
    $u->make_context = [IsEvenMakeContext::class, 'call'];
    $u->make_options = [IsEvenMakeOptions::class, 'call'];
    $u->make_request = [IsEvenMakeRequest::class, 'call'];
    $u->make_response = [IsEvenMakeResponse::class, 'call'];
    $u->make_result = [IsEvenMakeResult::class, 'call'];
    $u->make_point = [IsEvenMakePoint::class, 'call'];
    $u->make_spec = [IsEvenMakeSpec::class, 'call'];
    $u->make_url = [IsEvenMakeUrl::class, 'call'];
    $u->param = [IsEvenParam::class, 'call'];
    $u->prepare_auth = [IsEvenPrepareAuth::class, 'call'];
    $u->prepare_body = [IsEvenPrepareBody::class, 'call'];
    $u->prepare_headers = [IsEvenPrepareHeaders::class, 'call'];
    $u->prepare_method = [IsEvenPrepareMethod::class, 'call'];
    $u->prepare_params = [IsEvenPrepareParams::class, 'call'];
    $u->prepare_path = [IsEvenPreparePath::class, 'call'];
    $u->prepare_query = [IsEvenPrepareQuery::class, 'call'];
    $u->graphql_body = [IsEvenGraphql::class, 'body'];
    $u->graphql_errors = [IsEvenGraphql::class, 'errors'];
    $u->result_basic = [IsEvenResultBasic::class, 'call'];
    $u->result_body = [IsEvenResultBody::class, 'call'];
    $u->result_headers = [IsEvenResultHeaders::class, 'call'];
    $u->transform_request = [IsEvenTransformRequest::class, 'call'];
    $u->transform_response = [IsEvenTransformResponse::class, 'call'];
});
